name: idukaan
description: iDukaan

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  connectivity_plus: ^4.0.2
  flutter_secure_storage: ^9.0.0
  file_picker: ^10.2.0
  image_picker: ^1.0.4
  geolocator: ^14.0.2
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/intro/
